export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FET_INGREDIENT_FAILED = 'FET_INGREDIENT_FAILED'
export const SEND_ORDER = 'SEND_ORDER'
export const SEND_ORDER_FAILED = 'SEND_ORDER_FAILED'
export const SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS'
export const ORDER_START = 'ORDER_START'
